---
- name: Provision ElasticSearch VagrantBox
  hosts: all
  sudo: yes
  remote_user: vagrant
  roles:
     - role: cmprescott.jre
     - role: denzuko-ansible-roles/elasticsearch

# vim:ft=ansible:sts=4:ts=4:et:cin:ai:sw=4:
